/**
 * Url : https://www.geeksforgeeks.org/encoding-a-sentence-into-pig-latin/#:~:text=A%20Pig%20Latin%20is%20an,%E2%80%9Cay%E2%80%9D%20to%20the%20end.
 * A Pig Latin is an encrypted word in English, generated by placing the first letter of each word at the end, and then adding “ay” to the end.
 *
 * Input : “nevermind youve got them”
 * Output : “evermindnay ouveyay otgay hemtay”
 *
 * */

const getPigEncodedValue = (word) => {
  const extractedString = word
    .split("")
    .splice(1, word.length - 1)
    .join("");
  return `${extractedString}${word.charAt(0)}ay`;
};

const getPigLatinEncoding = (inputString) => {
  if (inputString.trim().length === 0) return "Enter a valid string";

  return inputString
    .trim()
    .split(" ")
    .map((word) => getPigEncodedValue(word))
    .join(" ");
};

module.exports = getPigLatinEncoding;
